export const data = [
  {
      "Order ID": "CA-2016-106621",
      "Profit": "1.1808",
      "City": "Yuma",
      "Customer Name": "Dario Medina",
      "Product Name": "Newell 351",
      "Row ID": "8088",
      "Country": "United States",
      "Discount": "0.2",
      "Customer ID": "DM-12955",
      "Region": "West",
      "Quantity": "4",
      "Segment": "Corporate",
      "State": "Arizona",
      "Ship Mode": "Second Class",
      "Sub-Category": "Art",
      "Postal Code": "85364",
      "Ship Date": "10/1/2016",
      "Category": "Office Supplies",
      "Product ID": "OFF-AR-10002375",
      "Sales": "10.496",
      "Order Date": "9/29/2016"
  },
  {
      "Order ID": "CA-2015-107902",
      "Profit": "122.2936",
      "City": "Fairfield",
      "Customer Name": "Suzanne McNair",
      "Product Name": "SAFCO Mobile Desk Side File, Wire Frame",
      "Row ID": "9693",
      "Country": "United States",
      "Discount": "0",
      "Customer ID": "SM-20950",
      "Region": "East",
      "Quantity": "11",
      "Segment": "Corporate",
      "State": "Connecticut",
      "Ship Mode": "Standard Class",
      "Sub-Category": "Storage",
      "Postal Code": "6824",
      "Ship Date": "9/2/2015",
      "Category": "Office Supplies",
      "Product ID": "OFF-ST-10001837",
      "Sales": "470.36",
      "Order Date": "8/28/2015"
  },
];
